## Deliverable 3. Create a Travel Itinerary Map.

In [239]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import gmaps.datasets

# Import API key
from config import g_key

import os

# Configure gmaps
gmaps.configure(api_key=g_key)

In [240]:
# Create the filepath for the csv
file_to_load = os.path.join("..","Weather_Database", "WeatherPy_vacation.csv")

In [241]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv(file_to_load)
vacation_df.head()

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,2,Huarmey,PE,76.26,Broken Clouds,-10.0681,-78.1522,Hotel Miramar
1,4,Lorengau,PG,80.76,Overcast Clouds,-2.0226,147.2712,Lorengau Harbourside Hotel
2,6,Carnarvon,AU,82.47,Scattered Clouds,-24.8667,113.6333,Hospitality Carnarvon
3,8,Hithadhoo,MV,81.81,Overcast Clouds,-0.6000,73.0833,Scoop Guest House
4,10,Saint-Philippe,RE,78.39,Few Clouds,-21.3585,55.7679,"Chambres d'hôte ""La Trinité"""

In [242]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [243]:
# 4a. Add a marker layer for each city to the map.
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
# 4b. Display the figure
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
fig.add_layer(marker_layer)
fig

Figure(layout=FigureLayout(height='420px'))

In [244]:
vacation_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,2,Huarmey,PE,76.26,Broken Clouds,-10.0681,-78.1522,Hotel Miramar
1,4,Lorengau,PG,80.76,Overcast Clouds,-2.0226,147.2712,Lorengau Harbourside Hotel
2,6,Carnarvon,AU,82.47,Scattered Clouds,-24.8667,113.6333,Hospitality Carnarvon
3,8,Hithadhoo,MV,81.81,Overcast Clouds,-0.6000,73.0833,Scoop Guest House
4,10,Saint-Philippe,RE,78.39,Few Clouds,-21.3585,55.7679,"Chambres d'hôte ""La Trinité"""
...,...,...,...,...,...,...,...,...
194,662,Bengkulu,ID,76.78,Overcast Clouds,-3.8004,102.2655,Grage Hotel Bengkulu
195,675,Cairns,AU,78.75,Scattered Clouds,-16.9167,145.7667,Mantra Trilogy Cairns
196,676,Mvangue,CM,85.71,Few Clouds,2.9667,11.5167,NaN
197,682,Pilar,BR,87.73,Broken Clouds,-9.5972,-35.9567,Pousada e churrascaria Manguaba
198,683,Jutai,BR,84.90,Overcast Clouds,-5.1833,-68.9000,NaN

In [245]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[(vacation_df["City"] == "Kota Bahru")]
vacation_end =   vacation_df.loc[(vacation_df["City"] == "Kota Bahru")]
vacation_stop1 = vacation_df.loc[(vacation_df["City"] == "Marang")]
vacation_stop2 = vacation_df.loc[(vacation_df["City"] == "Cukai")]
vacation_stop3 = vacation_df.loc[(vacation_df["City"] == "Georgetown")]

In [246]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.

# [(1, 3), (3, 6), (5, 7), (6, 4), (7, 8)]
start = [tuple(r) for r in vacation_start[['Lat','Lng']].to_numpy()]
end = [tuple(r) for r in vacation_end[['Lat','Lng']].to_numpy()]
stop1 = [tuple(r) for r in vacation_stop1[['Lat','Lng']].to_numpy()]
stop2 = [tuple(r) for r in vacation_stop2[['Lat','Lng']].to_numpy()]
stop3 = [tuple(r) for r in vacation_stop3[['Lat','Lng']].to_numpy()]

for s in start:
    start = s

for e in end:
    end = e
    
for stop in stop1:
    stop1 = stop

for stop in stop2:
    stop2 = stop

for stop in stop3:
    stop3 = stop

In [247]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".

# Latitude-longitude pairs
Kota_Bahru = start
Kota_Bahru = end
Marang = stop1
Cukai = stop2
Georgetown = stop3

directions_layer = gmaps.directions_layer(Kota_Bahru, Kota_Bahru, waypoints = [Marang, Cukai, Georgetown])

Georgetown

(5.4112, 100.3354)

In [248]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, vacation_stop2, vacation_stop3],ignore_index=True)
itinerary_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,160,Kota Bahru,MY,76.98,Light Rain,6.1333,102.2386,Grand Riverview Hotel
1,374,Marang,MY,75.11,Overcast Clouds,5.2056,103.2059,DBarakah Homestay
2,336,Cukai,MY,75.15,Overcast Clouds,4.2500,103.4167,OYO 90038 Dalyla Inn Chalet
3,16,Georgetown,MY,82.89,Few Clouds,5.4112,100.3354,Cititel Penang

In [249]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [250]:
# 11a. Add a marker layer for each city to the map.
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

# 11b. Display the figure
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
#fig.add_layer(directions_layer)
fig.add_layer(marker_layer)
fig

Figure(layout=FigureLayout(height='420px'))

In [251]:
# 11a. Add a marker layer for each city to the map.
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

# 11b. Display the figure
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
fig.add_layer(directions_layer)
fig.add_layer(marker_layer)
fig

Figure(layout=FigureLayout(height='420px'))